### ISSUE TITLE
ROA support in biblatex

### ISSUE THREAD

**Issue by natalieweber** [jcrippen/texnologue#1]
I can't figure out how to branch, but here's an addition I'd like to see to lsalike.bbx: support for  eprinttype={roa} (Rutgers Optimality Archive). Unfortunately the ROA number associated with a paper is not the same as the archive-internal number used in the URL. But biblatex also offers an eprintclass field that we can utilize. 

Here's my suggested addition to lsalike.bbx:

```
% ROA will print with other eprint items.
\DeclareFieldFormat{eprint:roa}{%
  \mkbibacro{ROA}\acronymcolon\space
  \ifhyperref
    {% The ROA number is not the same as the number used in the URL. 
     % Only create a hyperlink if the eprintclass field is filled.
        \iffieldundef{eprintclass}%
        	{\nolinkurl{#1}}%
        	{\href{http://roa.rutgers.edu/article/view/\thefield{eprintclass}}{\nolinkurl{#1}}}%
    }%
    {\nolinkurl{#1}}%
}
\DeclareFieldAlias{eprint:ROA}{eprint:roa}
```

**Comment by jcrippen** [comment]
Thanks!

**Comment by natalieweber** [comment]
Sweet! That was fun.


--

Natalie Weber

PhD candidate
Department of Linguistics
University of British Columbia
